// <auto-generated />
using System;
using GL.GestionVentas.Repositories.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace GL.GestionVentas.Repositories.Migrations
{
    [DbContext(typeof(GestionVentasContext))]
    [Migration("20200507041218_Init")]
    partial class Init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("GL.GestionVentas.Domain.Entities.Carrito", b =>
                {
                    b.Property<int>("CarritoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("ClienteId")
                        .HasColumnType("int");

                    b.HasKey("CarritoId");

                    b.HasIndex("ClienteId");

                    b.ToTable("Carrito");

                    b.HasData(
                        new
                        {
                            CarritoId = 1,
                            ClienteId = 1
                        },
                        new
                        {
                            CarritoId = 2,
                            ClienteId = 2
                        });
                });

            modelBuilder.Entity("GL.GestionVentas.Domain.Entities.CarritoProducto", b =>
                {
                    b.Property<int>("CarritoProductoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:IdentityIncrement", 1)
                        .HasAnnotation("SqlServer:IdentitySeed", 1)
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CarritoId")
                        .HasColumnType("int");

                    b.Property<int>("ProductoId")
                        .HasColumnType("int");

                    b.HasKey("CarritoProductoId");

                    b.HasIndex("CarritoId");

                    b.HasIndex("ProductoId");

                    b.ToTable("CarritoProducto");

                    b.HasData(
                        new
                        {
                            CarritoProductoId = 1,
                            CarritoId = 1,
                            ProductoId = 3
                        },
                        new
                        {
                            CarritoProductoId = 2,
                            CarritoId = 1,
                            ProductoId = 4
                        },
                        new
                        {
                            CarritoProductoId = 3,
                            CarritoId = 2,
                            ProductoId = 3
                        });
                });

            modelBuilder.Entity("GL.GestionVentas.Domain.Entities.Cliente", b =>
                {
                    b.Property<int>("ClienteId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:IdentityIncrement", 1)
                        .HasAnnotation("SqlServer:IdentitySeed", 1)
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasColumnType("nvarchar(45)")
                        .HasMaxLength(45);

                    b.Property<string>("DNI")
                        .IsRequired()
                        .HasColumnType("nvarchar(10)")
                        .HasMaxLength(10);

                    b.Property<string>("Direccion")
                        .IsRequired()
                        .HasColumnType("nvarchar(45)")
                        .HasMaxLength(45);

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(45)")
                        .HasMaxLength(45);

                    b.Property<string>("Telefono")
                        .HasColumnType("nvarchar(45)")
                        .HasMaxLength(45);

                    b.HasKey("ClienteId");

                    b.ToTable("Cliente");

                    b.HasData(
                        new
                        {
                            ClienteId = 1,
                            Apellido = "Perez",
                            DNI = "30000001",
                            Direccion = "Calle falsa 123",
                            Nombre = "Roberto",
                            Telefono = "12345678"
                        },
                        new
                        {
                            ClienteId = 2,
                            Apellido = "Fulanito",
                            DNI = "40000001",
                            Direccion = "Av. Mitre 123",
                            Nombre = "Cosme",
                            Telefono = "12345555"
                        },
                        new
                        {
                            ClienteId = 3,
                            Apellido = "Rodriguez",
                            DNI = "50000001",
                            Direccion = "Calchaqui 3000",
                            Nombre = "Patricia",
                            Telefono = "11111111"
                        });
                });

            modelBuilder.Entity("GL.GestionVentas.Domain.Entities.Producto", b =>
                {
                    b.Property<int>("ProductoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:IdentityIncrement", 1)
                        .HasAnnotation("SqlServer:IdentitySeed", 1)
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasColumnType("nvarchar(45)")
                        .HasMaxLength(45);

                    b.Property<string>("Marca")
                        .HasColumnType("nvarchar(45)")
                        .HasMaxLength(45);

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(45)")
                        .HasMaxLength(45);

                    b.Property<decimal>("Precio")
                        .HasColumnType("decimal(15,2)");

                    b.HasKey("ProductoId");

                    b.HasIndex("Codigo")
                        .IsUnique();

                    b.ToTable("Producto");

                    b.HasData(
                        new
                        {
                            ProductoId = 1,
                            Codigo = "MOU",
                            Marca = "Noganet",
                            Nombre = "Mouse",
                            Precio = 10m
                        },
                        new
                        {
                            ProductoId = 2,
                            Codigo = "CAM",
                            Nombre = "Camara",
                            Precio = 15m
                        },
                        new
                        {
                            ProductoId = 3,
                            Codigo = "TEC",
                            Marca = "Noganet",
                            Nombre = "Teclado",
                            Precio = 20m
                        },
                        new
                        {
                            ProductoId = 4,
                            Codigo = "MON",
                            Marca = "Samsung",
                            Nombre = "Monitor",
                            Precio = 38m
                        },
                        new
                        {
                            ProductoId = 5,
                            Codigo = "CPU",
                            Marca = "Gigabit",
                            Nombre = "CPU",
                            Precio = 250m
                        });
                });

            modelBuilder.Entity("GL.GestionVentas.Domain.Entities.Ventas", b =>
                {
                    b.Property<int>("VentasId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:IdentityIncrement", 1)
                        .HasAnnotation("SqlServer:IdentitySeed", 1)
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CarritoId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime");

                    b.HasKey("VentasId");

                    b.HasIndex("CarritoId");

                    b.ToTable("Ventas");

                    b.HasData(
                        new
                        {
                            VentasId = 1,
                            CarritoId = 1,
                            Fecha = new DateTime(2020, 5, 7, 1, 12, 17, 630, DateTimeKind.Local).AddTicks(1415)
                        },
                        new
                        {
                            VentasId = 2,
                            CarritoId = 1,
                            Fecha = new DateTime(2020, 5, 7, 1, 12, 17, 631, DateTimeKind.Local).AddTicks(9391)
                        },
                        new
                        {
                            VentasId = 3,
                            CarritoId = 2,
                            Fecha = new DateTime(2020, 5, 7, 1, 12, 17, 631, DateTimeKind.Local).AddTicks(9494)
                        });
                });

            modelBuilder.Entity("GL.GestionVentas.Domain.Entities.Carrito", b =>
                {
                    b.HasOne("GL.GestionVentas.Domain.Entities.Cliente", "Cliente")
                        .WithMany("Carritos")
                        .HasForeignKey("ClienteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("GL.GestionVentas.Domain.Entities.CarritoProducto", b =>
                {
                    b.HasOne("GL.GestionVentas.Domain.Entities.Carrito", "Carrito")
                        .WithMany("CarritoProductos")
                        .HasForeignKey("CarritoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GL.GestionVentas.Domain.Entities.Producto", "Producto")
                        .WithMany("CarritoProductos")
                        .HasForeignKey("ProductoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("GL.GestionVentas.Domain.Entities.Ventas", b =>
                {
                    b.HasOne("GL.GestionVentas.Domain.Entities.Carrito", "Carrito")
                        .WithMany("Ventas")
                        .HasForeignKey("CarritoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
